apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: decidim-an-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decidim-an-deployment
  minReplicas: 4
  maxReplicas: 24
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
