apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-an-deployment
spec:
  selector:
    matchLabels:
      app: decidim-an-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: decidim-an-app
    spec:
      terminationGracePeriodSeconds: 60
      tolerations:
      - key: "k8s.scaleway.com/dedicated"
        value: "decidim-app"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node.libre.sh/roles
                operator: DoesNotExist
            weight: 20
          - preference:
              matchExpressions:
              - key: node.libre.sh/roles
                operator: NotIn
                values:
                - postgres
            weight: 100
          - preference:
              matchExpressions:
              - key: node.libre.sh/roles
                operator: NotIn
                values:
                - minio
            weight: 80
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: htpasswd
        secret:
          secretName: htpasswd
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: 
          requests:
            cpu: "5m"
            memory: "20Mi"
          limits:
            memory: "50Mi"
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: htpasswd
          mountPath: "/etc/nginx-secret/"
          readOnly: true
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        startupProbe:
          failureThreshold: 11
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5 && /usr/sbin/nginx -s quit"]
      - name: app
        image: rg.fr-par.scw.cloud/decidim-an/decidim-an:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 450Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health_check
            port: 3000
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health_check
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        startupProbe:
          failureThreshold: 11
          httpGet:
            path: /health_check
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep", "5"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: decidim-an-app-config
        - secretRef:
            name: decidim-an-app-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: decidim-an-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decidim-an-deployment
  minReplicas: 3
  maxReplicas: 80
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80