apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: pp-an
  name: decidim-an-ingress
spec:
  rules:
    - host: ppan-pprod.opensourcepolitics.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: decidim-an-svc
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: decidim-an-svc
spec:
  selector:
    app: decidim-an-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
